### PR TITLE
make print errors optional

### PR DESCRIPTION
**Pull request by ma-ji**

### CODE REVIEW

**Comment by EnginEken** [comment]
hey @ma-ji, apologies for the recent inactivity due to personal and work changes. I'm back now and will be reviewing this PR.

**Comment by EnginEken** [comment]
Hey @ma-ji again, could you please explain why did you need to make the error print optional? I am just curious about the reason.

**Comment by ma-ji** [comment]
Thanks for working on this!

Sometimes I don't need the logs printed out and the printing may
slow things down, that's why I suggested an option to disable it.

sent from mobile.

**Comment by DeflateAwning** [comment]
Can we merge this?

**Comment by EnginEken** [comment]
Hi @ma-ji,

This option is now merged to the main branch with #23 

This will be available in the next release. 

Thanks for the contribution. Closing the PR...

**Pull request closed without merging**
